// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SiteOverseer.Data;

#nullable disable

namespace SiteOverseer.Migrations
{
    [DbContext(typeof(SiteDbContext))]
    [Migration("20240621071354_CreateFacilityProgressHistoryTable")]
    partial class CreateFacilityProgressHistoryTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FacilityProgressHistory", b =>
                {
                    b.Property<long>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("HistoryId"));

                    b.Property<long>("FacilityProgressId")
                        .HasColumnType("bigint");

                    b.Property<string>("ImageContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("ProgPercent")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("HistoryId");

                    b.HasIndex("FacilityProgressId");

                    b.ToTable("FacilityProgressHistories");
                });

            modelBuilder.Entity("SiteOverseer.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<string>("CityCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CityName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<short>("CmpyId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("RevDtetime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CityId");

                    b.ToTable("MS_City");
                });

            modelBuilder.Entity("SiteOverseer.Models.Company", b =>
                {
                    b.Property<short>("CmpyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("CmpyId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CmpyNme")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("RevDtetime")
                        .HasColumnType("datetime2");

                    b.HasKey("CmpyId");

                    b.ToTable("MS_Company");
                });

            modelBuilder.Entity("SiteOverseer.Models.Contractor", b =>
                {
                    b.Property<int>("CntorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CntorId"));

                    b.Property<bool>("BadStatus")
                        .HasColumnType("bit");

                    b.Property<short>("CmpyId")
                        .HasColumnType("smallint");

                    b.Property<string>("CntorNme")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("Establisheddte")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FciltypId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("ProgpayId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RevDtetime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CntorId");

                    b.ToTable("MS_Contractor");
                });

            modelBuilder.Entity("SiteOverseer.Models.Facility", b =>
                {
                    b.Property<int>("FcilId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FcilId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ApproveDte")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<int?>("CityId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<short>("CmpyId")
                        .HasColumnType("smallint");

                    b.Property<decimal?>("Contractval")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FcilCde")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FcilNme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FcilstartDte")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<int?>("FciltypId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime>("RevdTetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Township")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("FcilId");

                    b.ToTable("MS_Facility");
                });

            modelBuilder.Entity("SiteOverseer.Models.FacilityProgress", b =>
                {
                    b.Property<long>("ProgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProgId"));

                    b.Property<short?>("CmpyId")
                        .HasColumnType("smallint");

                    b.Property<int?>("FcilTskId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("ImageContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<short?>("ProgPercent")
                        .IsRequired()
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("RevDteTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SubmitDte")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ProgId");

                    b.ToTable("PMS_Facilityprogress");
                });

            modelBuilder.Entity("SiteOverseer.Models.FacilityProgressDocument", b =>
                {
                    b.Property<long>("DocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DocId"));

                    b.Property<short>("CmpyId")
                        .HasColumnType("smallint");

                    b.Property<int>("ProgId")
                        .HasColumnType("int");

                    b.Property<byte[]>("ProgImg")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("RevDteTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("DocId");

                    b.ToTable("PMS_Facilityprogressdocument");
                });

            modelBuilder.Entity("SiteOverseer.Models.FacilityProgressImage", b =>
                {
                    b.Property<long>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ImageId"));

                    b.Property<long>("FacilityProgressId")
                        .HasColumnType("bigint");

                    b.Property<string>("ImageContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ImageId");

                    b.HasIndex("FacilityProgressId");

                    b.ToTable("FacilityProgressImages");
                });

            modelBuilder.Entity("SiteOverseer.Models.FacilityTask", b =>
                {
                    b.Property<int>("FciltskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FciltskId"));

                    b.Property<bool>("AllowSubmitExpense")
                        .HasColumnType("bit");

                    b.Property<decimal?>("AwardedValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Budget")
                        .IsRequired()
                        .HasColumnType("decimal(18,2)");

                    b.Property<short>("CmpyId")
                        .HasColumnType("smallint");

                    b.Property<int?>("CntorId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("FcilId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("ProgpayId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RevdTetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SelectionTyp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TaskCompleteFlg")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("WbsdId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime?>("WorkendDte")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("WorkstartDte")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.HasKey("FciltskId");

                    b.ToTable("MS_Facilitytask");
                });

            modelBuilder.Entity("SiteOverseer.Models.FacilityTranLog", b =>
                {
                    b.Property<long>("TrLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TrLogId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ClaimDteTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ClaimFlg")
                        .HasColumnType("bit");

                    b.Property<short>("CmpyId")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("DeleteDteTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DeleteFlg")
                        .HasColumnType("bit");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<int>("FcilTskId")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RevDteTime")
                        .HasColumnType("datetime2");

                    b.Property<short>("TranReasonId")
                        .HasColumnType("smallint");

                    b.Property<short>("TranTypId")
                        .HasColumnType("smallint");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TrLogId");

                    b.ToTable("PMS_Facilitytranlog");
                });

            modelBuilder.Entity("SiteOverseer.Models.FacilityType", b =>
                {
                    b.Property<int>("FciltypId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FciltypId"));

                    b.Property<short>("CmpyId")
                        .HasColumnType("smallint");

                    b.Property<string>("FciltypCde")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FciltypDesc")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("RevdTetime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("FciltypId");

                    b.ToTable("MS_Facilitytype");
                });

            modelBuilder.Entity("SiteOverseer.Models.Menuaccess", b =>
                {
                    b.Property<int>("AccessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccessId"));

                    b.Property<string>("BtnNme")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<short>("MnugrpId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("RevdTetime")
                        .HasColumnType("datetime2");

                    b.HasKey("AccessId");

                    b.ToTable("MS_Menuaccess");
                });

            modelBuilder.Entity("SiteOverseer.Models.Menugp", b =>
                {
                    b.Property<short>("MnugrpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("MnugrpId"));

                    b.Property<string>("MnugrpNme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RevdTetime")
                        .HasColumnType("datetime2");

                    b.HasKey("MnugrpId");

                    b.ToTable("MS_Menugp");
                });

            modelBuilder.Entity("SiteOverseer.Models.TranTypeCode", b =>
                {
                    b.Property<short>("TrantypId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("TrantypId"));

                    b.Property<short>("CmpyId")
                        .HasColumnType("smallint");

                    b.Property<bool>("ContractorFlg")
                        .HasColumnType("bit");

                    b.Property<bool>("RequireClaim")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RevDtetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("TranNature")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("TrantypCde")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TrantypId");

                    b.ToTable("MS_Trantypecode");
                });

            modelBuilder.Entity("SiteOverseer.Models.TranTypeReason", b =>
                {
                    b.Property<short>("TranReasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("TranReasonId"));

                    b.Property<short>("CmpyId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("RevDtetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("TranReasonDesc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TranReasonId");

                    b.ToTable("MS_Trantypereason");
                });

            modelBuilder.Entity("SiteOverseer.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<short>("CmpyId")
                        .HasColumnType("smallint");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<short>("MnugrpId")
                        .HasColumnType("smallint");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("Pwd")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("RevdTetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserCde")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("UserNme")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.ToTable("MS_User");
                });

            modelBuilder.Entity("SiteOverseer.Models.Wbs", b =>
                {
                    b.Property<int>("WbsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WbsId"));

                    b.Property<short>("CmpyId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("RevdTetime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("WbsCde")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("WbsId");

                    b.ToTable("MS_Wbs");
                });

            modelBuilder.Entity("SiteOverseer.Models.WbsDetail", b =>
                {
                    b.Property<int>("WbsdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WbsdId"));

                    b.Property<short>("CmpyId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("RevdTetime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WbsId")
                        .HasColumnType("int");

                    b.Property<string>("WbsdCde")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("WbsdId");

                    b.ToTable("MS_Wbsdetail");
                });

            modelBuilder.Entity("FacilityProgressHistory", b =>
                {
                    b.HasOne("SiteOverseer.Models.FacilityProgress", "FacilityProgress")
                        .WithMany("ProgressHistory")
                        .HasForeignKey("FacilityProgressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FacilityProgress");
                });

            modelBuilder.Entity("SiteOverseer.Models.FacilityProgressImage", b =>
                {
                    b.HasOne("SiteOverseer.Models.FacilityProgress", "FacilityProgress")
                        .WithMany("Images")
                        .HasForeignKey("FacilityProgressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FacilityProgress");
                });

            modelBuilder.Entity("SiteOverseer.Models.FacilityProgress", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("ProgressHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
